---
- name: Check if SSL certificate was created
  stat:
    path: etc/ssl/private/{{ inventory_hostname }}.key
  register: ssl_key

- name: Generate self-signed SSL certificate for Apache
  command: >2
    openssl req
    -x509
    -nodes
    -days 3650
    -newkey rsa:2048
    -keyout /etc/ssl/private/{{ inventory_hostname }}.key
    -out /etc/ssl/certs/{{ inventory_hostname }}.crt
    -subj "/C=US/ST=Colorado/L=Colorado Springs/O=MDN/CN={{ inventory_hostname }}"
  when: not ssl_key.stat.exists and not custom_certificate

- name: Copy Custom SSL Certificate
  block:
    - name: Copy Certificate
      copy:
        src: "{{ inventory_dir }}/secure/certificates/{{ inventory_hostname }}.crt"
        dest: "/etc/ssl/certs/{{ inventory_hostname }}.crt"
        force: yes
        owner: root
        group: root
        mode: '644'
    - name: Copy Private Key
      copy:
        src: "{{ inventory_dir }}/secure/certificates/{{ inventory_hostname }}.key"
        dest: "/etc/ssl/private/{{ inventory_hostname }}.key"
        force: yes
        owner: root
        group: root
        mode: '600'
  when: custom_certificate

- name: Apache WordPress Configuration
  template:
    src: wordpress.conf.j2
    dest: "/etc/apache2/sites-available/wordpress.conf"
    owner: root
    group: root
    mode: '644'
  register: apache_configuration

- name: Disable 000-default.conf
  command: a2dissite 000-default.conf

- name: Enable wordpress.conf
  command: a2ensite wordpress.conf

- name: Restart Apache
  service:
    name: "apache2"
    state: restarted
    enabled: yes
  when: apache_configuration.changed

- name: nftwables wordpress ports
  template:
    src: wordpress.nft.j2
    dest: /etc/nftables.d/input/wordpress.nft
    owner: root
    group: root
    mode: '644'
  register: nftables_configuration

- name: Validate nftables
  command: "nft -c -f /etc/nftables.conf"
  register: nft_validation
  failed_when: false
  when: nftables_configuration.changed

- name: Remove wordpress.nft if validation failed
  file:
    path: /etc/nftables.d/input/wordpress.nft
    state: absent
  when: nftables_configuration.changed and nft_validation.rc != 0

- name: Apply nftables Configuration
  command: "nft -f /etc/nftables.conf"
  when: nftables_configuration.changed and nft_validation.rc == 0

- name: Fail if nftables validation failed
  fail:
    msg: "Error: {{ nft_validation.stderr | default('nftables error') }}"
  when: nftables_configuration.changed and nft_validation.rc != 0

- name: Redis Object Cache
  pause:
    prompt: "Make sure to install the `Redis Object Cache` plugin. Press enter to continue."